# Generated by Django 5.1.3 on 2025-01-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course_eduction_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eduction',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
