# Generated by Django 5.1.3 on 2025-01-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projects_duration_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cart',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='shipping',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='wishlist',
            field=models.ImageField(null=True, upload_to='static/image'),
        ),
    ]
