# Generated by Django 5.1.3 on 2025-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_course_image_alter_projects_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Phone',
            field=models.BigIntegerField(),
        ),
    ]
