# Generated by Django 5.1.3 on 2025-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
