# Generated by Django 5.1.3 on 2025-01-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_projects_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
